/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package obernardovieira.dimusique.frames;

import java.util.ArrayList;
import javax.swing.JFrame;
import obernardovieira.dimusique.MainWindows;
import obernardovieira.dimusique.core.Data;
import obernardovieira.dimusique.core.Playlist;

/**
 *
 * @author user
 */
public class FramePlaylists extends javax.swing.JPanel {

    /**
     * Creates new form FramePlaylists
     */
    private final MainWindows window;
    public FramePlaylists(JFrame window)
    {
        initComponents();
        this.window = (MainWindows)window;
        ArrayList<Playlist> playlists = Data.loadData();
        
        if(playlists.isEmpty())
        {
            panel_playlists.add(new FrameNoData(window));
        }
        else
        {
            playlists.forEach((element) -> {
                panel_playlists.add(new FramePlaylistsElement(element));
            });
        }
        panel_playlists.invalidate();
        panel_playlists.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_title = new javax.swing.JLabel();
        scrollpane_playlists = new javax.swing.JScrollPane();
        panel_playlists = new javax.swing.JPanel();

        label_title.setFont(new java.awt.Font("Yu Gothic Light", 0, 28)); // NOI18N
        label_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_title.setText("You playlists");

        scrollpane_playlists.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        panel_playlists.setLayout(new javax.swing.BoxLayout(panel_playlists, javax.swing.BoxLayout.Y_AXIS));
        scrollpane_playlists.setViewportView(panel_playlists);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_title, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
            .addComponent(scrollpane_playlists)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(label_title, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollpane_playlists, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label_title;
    private javax.swing.JPanel panel_playlists;
    private javax.swing.JScrollPane scrollpane_playlists;
    // End of variables declaration//GEN-END:variables
}
