/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package obernardovieira.dimusique.frames;

/**
 *
 * @author user
 */
public class FrameControls extends javax.swing.JPanel {

    /**
     * Creates new form FramePlaying
     */
    public FrameControls() {
        initComponents();
        panel_disc_image.add(new PicPanel("src/main/resources/images/disk2.png",
                256, 256, 95, 95, panel_controls.getBackground()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_disc_image = new javax.swing.JPanel();
        lb_current_time = new javax.swing.JLabel();
        pb_music = new javax.swing.JProgressBar();
        lb_total_time = new javax.swing.JLabel();
        panel_controls = new javax.swing.JPanel();
        button_previous = new javax.swing.JButton();
        button_next = new javax.swing.JButton();
        button_stop = new javax.swing.JButton();
        button_pause = new javax.swing.JButton();
        button_play = new javax.swing.JButton();
        label_music_name = new javax.swing.JLabel();
        label_artist_name = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 204));

        panel_disc_image.setBackground(new java.awt.Color(204, 255, 204));
        panel_disc_image.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout panel_disc_imageLayout = new javax.swing.GroupLayout(panel_disc_image);
        panel_disc_image.setLayout(panel_disc_imageLayout);
        panel_disc_imageLayout.setHorizontalGroup(
            panel_disc_imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel_disc_imageLayout.setVerticalGroup(
            panel_disc_imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );

        lb_current_time.setText("4:51");

        pb_music.setValue(37);

        lb_total_time.setText("6:23");

        panel_controls.setBackground(getBackground());

        button_previous.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/controls/137__previous.png"))); // NOI18N
        button_previous.setToolTipText("Previous");

        button_next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/controls/136__next.png"))); // NOI18N
        button_next.setToolTipText("Next");

        button_stop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/controls/133__stop.png"))); // NOI18N
        button_stop.setToolTipText("Stop");

        button_pause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/controls/132__pause.png"))); // NOI18N
        button_pause.setToolTipText("Pause");

        button_play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/controls/131__play.png"))); // NOI18N
        button_play.setToolTipText("Play");
        button_play.setBorder(null);
        button_play.setBorderPainted(false);
        button_play.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        label_music_name.setText("Music name");

        label_artist_name.setText("Artist name");

        javax.swing.GroupLayout panel_controlsLayout = new javax.swing.GroupLayout(panel_controls);
        panel_controls.setLayout(panel_controlsLayout);
        panel_controlsLayout.setHorizontalGroup(
            panel_controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_controlsLayout.createSequentialGroup()
                .addComponent(label_music_name, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_previous, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_next, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_stop, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_pause, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_play, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panel_controlsLayout.createSequentialGroup()
                .addComponent(label_artist_name, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addGap(303, 303, 303))
        );
        panel_controlsLayout.setVerticalGroup(
            panel_controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_controlsLayout.createSequentialGroup()
                .addGroup(panel_controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_play, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_pause, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_stop, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_next, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_previous, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_controlsLayout.createSequentialGroup()
                        .addComponent(label_music_name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_artist_name)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_disc_image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_current_time)
                        .addGap(18, 18, 18)
                        .addComponent(pb_music, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(lb_total_time)
                        .addContainerGap())
                    .addComponent(panel_controls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_total_time)
                    .addComponent(pb_music, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_current_time))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_controls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_disc_image, 96, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_next;
    private javax.swing.JButton button_pause;
    private javax.swing.JButton button_play;
    private javax.swing.JButton button_previous;
    private javax.swing.JButton button_stop;
    private javax.swing.JLabel label_artist_name;
    private javax.swing.JLabel label_music_name;
    private javax.swing.JLabel lb_current_time;
    private javax.swing.JLabel lb_total_time;
    private javax.swing.JPanel panel_controls;
    private javax.swing.JPanel panel_disc_image;
    private javax.swing.JProgressBar pb_music;
    // End of variables declaration//GEN-END:variables
}
