/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package obernardovieira.vucor.frames;

import java.awt.Color;
import javax.swing.JFrame;
import obernardovieira.vucor.MainWindows;
import obernardovieira.vucor.core.Basic;

/**
 *
 * @author user
 */
public class FrameOptions extends javax.swing.JPanel {

    /**
     * Creates new form FrameOptions
     */
    private final MainWindows window;
    public FrameOptions(JFrame window)
    {
        initComponents();
        this.window = (MainWindows)window;
        
        to_playlist.add(new PicPanel("src/main/resources/images/options/140__music.png",
                167, 167, 60, 60, to_playlist.getParent().getBackground()));
        to_playlists.add(new PicPanel("src/main/resources/images/options/032__list_item.png",
                167, 167, 60, 60, to_playlists.getParent().getBackground()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        to_playlist = new javax.swing.JPanel();
        to_playlists = new javax.swing.JPanel();

        setBackground(new java.awt.Color(204, 204, 204));
        setMaximumSize(new java.awt.Dimension(60, 500));
        setMinimumSize(new java.awt.Dimension(10, 10));
        setPreferredSize(new java.awt.Dimension(60, 500));
        setRequestFocusEnabled(false);
        setVerifyInputWhenFocusTarget(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        to_playlist.setToolTipText("Show current playlist");
        to_playlist.setMaximumSize(new java.awt.Dimension(60, 60));
        to_playlist.setMinimumSize(new java.awt.Dimension(10, 10));
        to_playlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                to_playlistMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                to_playlistMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout to_playlistLayout = new javax.swing.GroupLayout(to_playlist);
        to_playlist.setLayout(to_playlistLayout);
        to_playlistLayout.setHorizontalGroup(
            to_playlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        to_playlistLayout.setVerticalGroup(
            to_playlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        add(to_playlist);

        to_playlists.setToolTipText("Show playlists");
        to_playlists.setMaximumSize(new java.awt.Dimension(60, 60));
        to_playlists.setMinimumSize(new java.awt.Dimension(10, 10));
        to_playlists.setPreferredSize(new java.awt.Dimension(60, 60));
        to_playlists.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                to_playlistsMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                to_playlistsMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout to_playlistsLayout = new javax.swing.GroupLayout(to_playlists);
        to_playlists.setLayout(to_playlistsLayout);
        to_playlistsLayout.setHorizontalGroup(
            to_playlistsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        to_playlistsLayout.setVerticalGroup(
            to_playlistsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        add(to_playlists);
    }// </editor-fold>//GEN-END:initComponents

    private void to_playlistMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_to_playlistMouseReleased
        window.setViewer(Basic.framePlaying);
        to_playlist.removeAll();
        to_playlist.add(new PicPanel("src/main/resources/images/options/140__music.png",
                167, 167, 60, 60, to_playlist.getParent().getBackground()));
        to_playlist.invalidate();
        to_playlist.repaint();
    }//GEN-LAST:event_to_playlistMouseReleased

    private void to_playlistsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_to_playlistsMouseReleased
        window.setViewer(Basic.framePlaylists);
        to_playlists.removeAll();
        to_playlists.add(new PicPanel("src/main/resources/images/options/032__list_item.png",
                167, 167, 60, 60, to_playlist.getParent().getBackground()));
        to_playlists.invalidate();
        to_playlists.repaint();
    }//GEN-LAST:event_to_playlistsMouseReleased

    private void to_playlistsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_to_playlistsMousePressed
        to_playlists.removeAll();
        to_playlists.add(new PicPanel("src/main/resources/images/options/032__list_item.png",
                167, 167, 60, 60, new Color(0,153,153)));
        to_playlists.invalidate();
        to_playlists.repaint();
    }//GEN-LAST:event_to_playlistsMousePressed

    private void to_playlistMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_to_playlistMousePressed
        to_playlist.removeAll();
        to_playlist.add(new PicPanel("src/main/resources/images/options/140__music.png",
                167, 167, 60, 60, new Color(0,153,153)));
        to_playlist.invalidate();
        to_playlist.repaint();
    }//GEN-LAST:event_to_playlistMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel to_playlist;
    private javax.swing.JPanel to_playlists;
    // End of variables declaration//GEN-END:variables
}
