/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package obernardovieira.vucor.frames;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javazoom.jl.decoder.JavaLayerException;
import obernardovieira.vucor.core.Model;
import obernardovieira.vucor.core.Playlist;
import obernardovieira.vucor.core.data.DataFiles;

/**
 *
 * @author user
 */
public class FrameControls extends javax.swing.JPanel {

    /**
     * Creates new form FramePlaying
     */
    private Model model;
    
    public FrameControls()
    {
        initComponents();
        panel_disc_image.add(new PicPanel(
                "src/main/resources/images/disk2.png",
                256, 256, 100, 100, panel_data.getBackground()));
        panel_previous.add(new PicPanel(
                "src/main/resources/images/controls/137__previous.png",
                167, 167, 60, 60, panel_data.getBackground()));
        panel_next.add(new PicPanel(
                "src/main/resources/images/controls/136__next.png",
                167, 167, 60, 60, panel_data.getBackground()));
        panel_stop.add(new PicPanel(
                "src/main/resources/images/controls/133__stop.png",
                167, 167, 60, 60, panel_data.getBackground()));
        panel_pause.add(new PicPanel(
                "src/main/resources/images/controls/132__pause.png",
                167, 167, 60, 60, panel_data.getBackground()));
        panel_play.add(new PicPanel(
                "src/main/resources/images/controls/131__play.png",
                167, 167, 60, 60, panel_data.getBackground()));
        panel_titles.setBackground(panel_data.getBackground());
        panel_time.setBackground(panel_data.getBackground());
        panel_controls.setBackground(panel_data.getBackground());
        
        try
        {
            model = new Model();
        }
        catch (IOException | ClassNotFoundException ex)
        {
            Logger.getLogger(FrameControls.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void addPlaylist(Playlist playlist)
    {
        model.addNewPlaylist(playlist);
        try
        {
            DataFiles.saveData(model.getDataModel());
        }
        catch (IOException ex)
        {
            Logger.getLogger(FrameControls.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void setPlaylistAndMusic(Playlist playlist, String music_name)
    {
        model.getDataModel().getPlaylists().forEach((playlist_) ->
        {
            playlist_.getNames().forEach((name_) ->
            {
                if(name_.equals(music_name))
                {
                    model.stopMusic();
                    model.changeToPlaylist(playlist_.getPlaylistName());
                    model.getDataModel().getCurrentPlaylist().setOnMusic(music_name);
                    try
                    {
                        model.playMusic();
                    }
                    catch (JavaLayerException | IOException ex)
                    { }
                }
            }); 
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_disc_image = new javax.swing.JPanel();
        panel_data = new javax.swing.JPanel();
        panel_time = new javax.swing.JPanel();
        label_cur_time = new javax.swing.JLabel();
        pb_music = new javax.swing.JProgressBar();
        label_total_time = new javax.swing.JLabel();
        panel_controls = new javax.swing.JPanel();
        panel_titles = new javax.swing.JPanel();
        lb_music_name = new javax.swing.JLabel();
        lb_artist_name = new javax.swing.JLabel();
        panel_previous = new javax.swing.JPanel();
        panel_next = new javax.swing.JPanel();
        panel_stop = new javax.swing.JPanel();
        panel_pause = new javax.swing.JPanel();
        panel_play = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(600, 100));
        setMinimumSize(new java.awt.Dimension(100, 100));
        setPreferredSize(new java.awt.Dimension(600, 100));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

        panel_disc_image.setBackground(new java.awt.Color(204, 255, 204));
        panel_disc_image.setMaximumSize(new java.awt.Dimension(100, 100));
        panel_disc_image.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout panel_disc_imageLayout = new javax.swing.GroupLayout(panel_disc_image);
        panel_disc_image.setLayout(panel_disc_imageLayout);
        panel_disc_imageLayout.setHorizontalGroup(
            panel_disc_imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel_disc_imageLayout.setVerticalGroup(
            panel_disc_imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        add(panel_disc_image);

        panel_data.setBackground(new java.awt.Color(255, 255, 255));
        panel_data.setMaximumSize(new java.awt.Dimension(500, 100));
        panel_data.setMinimumSize(new java.awt.Dimension(30, 30));
        panel_data.setPreferredSize(new java.awt.Dimension(500, 100));
        panel_data.setLayout(new javax.swing.BoxLayout(panel_data, javax.swing.BoxLayout.Y_AXIS));

        panel_time.setMaximumSize(new java.awt.Dimension(450, 30));
        panel_time.setMinimumSize(new java.awt.Dimension(30, 30));
        panel_time.setPreferredSize(new java.awt.Dimension(450, 30));
        panel_time.setLayout(new javax.swing.BoxLayout(panel_time, javax.swing.BoxLayout.X_AXIS));

        label_cur_time.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_cur_time.setText("0:00");
        label_cur_time.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        label_cur_time.setMaximumSize(new java.awt.Dimension(40, 14));
        label_cur_time.setPreferredSize(new java.awt.Dimension(40, 14));
        panel_time.add(label_cur_time);

        pb_music.setMaximumSize(new java.awt.Dimension(370, 14));
        pb_music.setPreferredSize(new java.awt.Dimension(370, 14));
        panel_time.add(pb_music);

        label_total_time.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label_total_time.setText("4:63");
        label_total_time.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label_total_time.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        label_total_time.setMaximumSize(new java.awt.Dimension(40, 14));
        label_total_time.setPreferredSize(new java.awt.Dimension(40, 14));
        panel_time.add(label_total_time);

        panel_data.add(panel_time);

        panel_controls.setMaximumSize(new java.awt.Dimension(450, 70));
        panel_controls.setMinimumSize(new java.awt.Dimension(30, 30));
        panel_controls.setPreferredSize(new java.awt.Dimension(450, 70));
        panel_controls.setLayout(new javax.swing.BoxLayout(panel_controls, javax.swing.BoxLayout.X_AXIS));

        panel_titles.setBackground(new java.awt.Color(204, 255, 0));
        panel_titles.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel_titles.setPreferredSize(new java.awt.Dimension(150, 70));
        panel_titles.setLayout(new javax.swing.BoxLayout(panel_titles, javax.swing.BoxLayout.Y_AXIS));

        lb_music_name.setText("Music name");
        lb_music_name.setMaximumSize(new java.awt.Dimension(150, 35));
        lb_music_name.setPreferredSize(new java.awt.Dimension(150, 35));
        panel_titles.add(lb_music_name);

        lb_artist_name.setText("Artist name");
        lb_artist_name.setMaximumSize(new java.awt.Dimension(150, 35));
        lb_artist_name.setPreferredSize(new java.awt.Dimension(150, 35));
        panel_titles.add(lb_artist_name);

        panel_controls.add(panel_titles);

        panel_previous.setBackground(new java.awt.Color(204, 255, 0));
        panel_previous.setMaximumSize(new java.awt.Dimension(60, 60));
        panel_previous.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout panel_previousLayout = new javax.swing.GroupLayout(panel_previous);
        panel_previous.setLayout(panel_previousLayout);
        panel_previousLayout.setHorizontalGroup(
            panel_previousLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        panel_previousLayout.setVerticalGroup(
            panel_previousLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        panel_controls.add(panel_previous);

        panel_next.setBackground(new java.awt.Color(204, 255, 0));
        panel_next.setMaximumSize(new java.awt.Dimension(60, 60));
        panel_next.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout panel_nextLayout = new javax.swing.GroupLayout(panel_next);
        panel_next.setLayout(panel_nextLayout);
        panel_nextLayout.setHorizontalGroup(
            panel_nextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        panel_nextLayout.setVerticalGroup(
            panel_nextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        panel_controls.add(panel_next);

        panel_stop.setBackground(new java.awt.Color(204, 255, 0));
        panel_stop.setMaximumSize(new java.awt.Dimension(60, 60));
        panel_stop.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout panel_stopLayout = new javax.swing.GroupLayout(panel_stop);
        panel_stop.setLayout(panel_stopLayout);
        panel_stopLayout.setHorizontalGroup(
            panel_stopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        panel_stopLayout.setVerticalGroup(
            panel_stopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        panel_controls.add(panel_stop);

        panel_pause.setBackground(new java.awt.Color(204, 255, 0));
        panel_pause.setMaximumSize(new java.awt.Dimension(60, 60));
        panel_pause.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout panel_pauseLayout = new javax.swing.GroupLayout(panel_pause);
        panel_pause.setLayout(panel_pauseLayout);
        panel_pauseLayout.setHorizontalGroup(
            panel_pauseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        panel_pauseLayout.setVerticalGroup(
            panel_pauseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        panel_controls.add(panel_pause);

        panel_play.setBackground(new java.awt.Color(204, 255, 0));
        panel_play.setMaximumSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout panel_playLayout = new javax.swing.GroupLayout(panel_play);
        panel_play.setLayout(panel_playLayout);
        panel_playLayout.setHorizontalGroup(
            panel_playLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        panel_playLayout.setVerticalGroup(
            panel_playLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        panel_controls.add(panel_play);

        panel_data.add(panel_controls);

        add(panel_data);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label_cur_time;
    private javax.swing.JLabel label_total_time;
    private javax.swing.JLabel lb_artist_name;
    private javax.swing.JLabel lb_music_name;
    private javax.swing.JPanel panel_controls;
    private javax.swing.JPanel panel_data;
    private javax.swing.JPanel panel_disc_image;
    private javax.swing.JPanel panel_next;
    private javax.swing.JPanel panel_pause;
    private javax.swing.JPanel panel_play;
    private javax.swing.JPanel panel_previous;
    private javax.swing.JPanel panel_stop;
    private javax.swing.JPanel panel_time;
    private javax.swing.JPanel panel_titles;
    private javax.swing.JProgressBar pb_music;
    // End of variables declaration//GEN-END:variables
}
