/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package obernardovieira.dimusique.frames.elements;

/**
 *
 * @author user
 */
public class FramePlaylistElement extends javax.swing.JPanel {

    /**
     * Creates new form FramePlaylistElement
     * @param music_name
     */
    public FramePlaylistElement(String music_name)
    {
        initComponents();
        label_music_name.setText(music_name);
        label_music_name.invalidate();
        label_music_name.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_music_name = new javax.swing.JLabel();
        bt_play = new javax.swing.JButton();
        bt_remove = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

        label_music_name.setText("Music Name");
        label_music_name.setMaximumSize(new java.awt.Dimension(380, 14));
        label_music_name.setMinimumSize(new java.awt.Dimension(380, 14));
        label_music_name.setPreferredSize(new java.awt.Dimension(380, 14));
        add(label_music_name);

        bt_play.setText("Play");
        bt_play.setMaximumSize(new java.awt.Dimension(75, 23));
        bt_play.setMinimumSize(new java.awt.Dimension(75, 23));
        bt_play.setPreferredSize(new java.awt.Dimension(75, 23));
        add(bt_play);

        bt_remove.setText("Remove");
        bt_remove.setMaximumSize(new java.awt.Dimension(75, 23));
        bt_remove.setMinimumSize(new java.awt.Dimension(75, 23));
        bt_remove.setPreferredSize(new java.awt.Dimension(75, 23));
        add(bt_remove);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_play;
    private javax.swing.JButton bt_remove;
    private javax.swing.JLabel label_music_name;
    // End of variables declaration//GEN-END:variables
}
