/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package obernardovieira.dimusique.frames.elements;

/**
 *
 * @author user
 */
public class FrameNewPLElement extends javax.swing.JPanel {

    /**
     * Creates new form FrameNewPLElement
     */
    public FrameNewPLElement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_music_name = new javax.swing.JLabel();
        button_delete = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

        label_music_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_music_name.setText("Artist - Music name");
        label_music_name.setMaximumSize(new java.awt.Dimension(380, 35));
        add(label_music_name);

        button_delete.setText("Delete");
        add(button_delete);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_delete;
    private javax.swing.JLabel label_music_name;
    // End of variables declaration//GEN-END:variables
}
